# Generated by Django 5.2.8 on 2025-11-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internshipmain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                ("instructor", models.CharField(max_length=200)),
                ("rating", models.FloatField(default=0)),
                ("reviews_count", models.IntegerField(default=0)),
                ("language", models.CharField(default="English", max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_images/"
                    ),
                ),
            ],
        ),
    ]
