# Generated by Django 5.2.8 on 2025-11-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internshipmain", "0002_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
