# Generated by Django 5.2.8 on 2025-11-16 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("internshipmain", "0005_instructor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Instructor",
        ),
    ]
