# Generated by Django 5.2.8 on 2025-11-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internshipmain", "0007_instructor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructor",
            old_name="facebook",
            new_name="github",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="twitter",
        ),
        migrations.AddField(
            model_name="instructor",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="bio",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instructor",
            name="role",
            field=models.CharField(max_length=255),
        ),
    ]
