# Generated by Django 5.2.8 on 2025-11-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internshipmain", "0008_rename_facebook_instructor_github_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAbout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(default="About Internship Online", max_length=200),
                ),
                (
                    "subheading",
                    models.CharField(
                        default="Practical Learning • Real-World Projects • Career-Focused Internships",
                        max_length=300,
                    ),
                ),
                (
                    "section_title",
                    models.CharField(
                        default="Empowering Students in Computer Science",
                        max_length=200,
                    ),
                ),
                ("paragraph1", models.TextField(blank=True, null=True)),
                ("paragraph2", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
                (
                    "mission_title",
                    models.CharField(default="Our Mission", max_length=200),
                ),
                ("mission_text", models.TextField(blank=True, null=True)),
                (
                    "vision_title",
                    models.CharField(default="Our Vision", max_length=200),
                ),
                ("vision_text", models.TextField(blank=True, null=True)),
                (
                    "box1_title",
                    models.CharField(default="Hands-on Projects", max_length=200),
                ),
                ("box1_text", models.TextField(blank=True, null=True)),
                (
                    "box2_title",
                    models.CharField(
                        default="Learn from Expert Mentors", max_length=200
                    ),
                ),
                ("box2_text", models.TextField(blank=True, null=True)),
                (
                    "box3_title",
                    models.CharField(default="Certificate & Portfolio", max_length=200),
                ),
                ("box3_text", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
